/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Clases.ClsCandidato;
import Clases.ClsMensaje;
import Controladores.CtlCandidato;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;



/**
 *
 * @author larrc0
 */
public class VistaCandidato extends javax.swing.JFrame {
    JFrame menuPrincipal;
    CtlCandidato controladorCandidato;
    VistaPropuesta vistaPropuesta;
    public static String parametro = "";
    
    /**
     * Creates new form VistaCandidato
     */
    public VistaCandidato(JFrame menuPrincipal) {
        initComponents();
        this.menuPrincipal = menuPrincipal;
        this.controladorCandidato = new CtlCandidato();
        
        this.setDefaultCloseOperation(0);
        
        this.ObtenerCandidatos();
        this.EnabledControls(false);
        
        this.btnAdicionar.setEnabled(true);
        this.btnGuardar.setEnabled(false);
        this.btnEditar.setEnabled(true);
        this.btnActualizar.setEnabled(false);   
        this.btnCancelar.setEnabled(false); 
        
        //this.vistaPropuesta = new VistaPropuesta(this);

        
        // table header
        JTableHeader th = this.tblCanditados1.getTableHeader();
        th.setFont(new Font("Segoe UI", Font.BOLD, 15));
        th.setBackground(Color.black);
        th.setForeground(Color.yellow);        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCanditados1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnPropuestas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        cboxTipoDoc = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboxCiudad = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMensaje = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        cboxPartidoPolitico = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cboxCargos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestor del Candidato");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Listado de Candidatos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tblCanditados1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Partido Político"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCanditados1.setColumnSelectionAllowed(true);
        tblCanditados1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCanditados1.getTableHeader().setResizingAllowed(false);
        tblCanditados1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCanditados1MouseClicked(evt);
            }
        });
        tblCanditados1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblCanditados1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblCanditados1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblCanditados1KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(tblCanditados1);
        tblCanditados1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblCanditados1.getColumnModel().getColumnCount() > 0) {
            tblCanditados1.getColumnModel().getColumn(0).setMinWidth(0);
            tblCanditados1.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblCanditados1.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnPropuestas.setText("Propuestas");
        btnPropuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropuestasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPropuestas, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnPropuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Información del Candidato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel2.setText("Identificación:");

        txtIdentificacion.setDisabledTextColor(new java.awt.Color(0, 102, 102));

        cboxTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "CE", "NIP", "NIT", " " }));

        jLabel4.setText("Tipo de documento:");

        jLabel3.setText("Nombre:");

        txtNombre.setDisabledTextColor(new java.awt.Color(0, 102, 102));

        jLabel5.setText("Teléfono:");

        txtTelefono.setDisabledTextColor(new java.awt.Color(0, 102, 102));

        jLabel7.setText("eMail:");

        txtEmail.setDisabledTextColor(new java.awt.Color(0, 102, 102));

        jLabel6.setText("Ciudad de origen:");

        cboxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cartagena", "Barranquilla", "Santa Marta", "Riohacha", "Buenaventura", "Bogotá", "Medellín", "Cali" }));

        jLabel9.setText("Partido politico:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setDisabledTextColor(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel10.setText("Mensaje de Campaña:");

        txtMensaje.setColumns(20);
        txtMensaje.setRows(5);
        txtMensaje.setDisabledTextColor(new java.awt.Color(0, 102, 102));
        jScrollPane3.setViewportView(txtMensaje);

        jLabel8.setText("Descripción:");

        cboxPartidoPolitico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Partido Liberal Colombiano", "Partido Conservador Colombiano", "Partido Opción Ciudadana", "Partido Cambio Radical", "Partido Alianza Verde", "Movimiento Autoridades Indígenas de Colombia \"Aico\"", "PARTIDO ALIANZA SOCIAL INDEPENDIENTE \"ASI\"", "Movimiento \"Mira\"", "Partido Social de Unidad Nacional \"Partido de La U\"", "Partido Polo Democrático Alternativo", "PARTIDO UNION PATRIOTICA \"UP\"", "CENTRO DEMOCRATICO", "MOVIMIENTO ALTERNATIVO INDIGENA Y SOCIAL \"MAIS" }));

        jLabel11.setText("Cargo:");
        jLabel11.setToolTipText("");

        cboxCargos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presidente", "Diputado", "Gobernador", "Alcalde", "Consejal" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboxTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtEmail)
                            .addComponent(txtNombre)
                            .addComponent(cboxPartidoPolitico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboxCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(cboxTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cboxCiudad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxPartidoPolitico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cboxCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
        this.menuPrincipal.setVisible(true);        
    }//GEN-LAST:event_btnVolverActionPerformed

    private void tblCanditados1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCanditados1MouseClicked
        llenarCampos();
    }//GEN-LAST:event_tblCanditados1MouseClicked

    private void llenarCampos(){
        int fila = this.tblCanditados1.getSelectedRow();
        //int id = Integer.parseInt(this.tblCanditados1.getModel().getValueAt(selectedRow, 0).toString());
        String id = this.tblCanditados1.getValueAt(fila, 0).toString();
        //this.txtID.setText(String.valueOf(id));
        
        ClsCandidato candidato = this.controladorCandidato.recuperarCandidato(id);
        if (candidato != null){
            this.txtIdentificacion.setText(candidato.getNumeroDocumento());
            this.txtNombre.setText(candidato.getNombre());
            this.txtTelefono.setText(candidato.getTelefono());
            this.txtEmail.setText(candidato.getEmail());
            this.cboxCiudad.setSelectedItem(candidato.getCiudadorigen());
            this.cboxTipoDoc.setSelectedItem(candidato.getTipoDocumento());
            this.txtMensaje.setText(candidato.getMensajecampania());
            this.cboxPartidoPolitico.setSelectedItem(candidato.getPartidopolitico());
            this.txtDescripcion.setText(candidato.getDescripcion());
            this.txtMensaje.setText(candidato.getMensajecampania());
            this.cboxCargos.setSelectedItem(candidato.getCargo());
        }
    } 
    
    private void ClearControls(){
            this.txtIdentificacion.setText("");
            this.txtNombre.setText("");
            this.txtTelefono.setText("");
            this.txtEmail.setText("");
            this.cboxCiudad.setSelectedItem("");
            this.cboxTipoDoc.setSelectedItem("");
            this.txtMensaje.setText("");
            this.cboxPartidoPolitico.setSelectedItem("");
            this.txtDescripcion.setText("");
            this.txtMensaje.setText("");
    }
    private void EnabledControls(boolean flag){
            this.txtIdentificacion.setEnabled(flag);
            this.txtNombre.setEnabled(flag);
            this.txtTelefono.setEnabled(flag);
            this.txtEmail.setEnabled(flag);
            this.cboxCiudad.setEnabled(flag);
            this.cboxTipoDoc.setEnabled(flag);
            this.txtMensaje.setEnabled(flag);
            this.cboxPartidoPolitico.setEnabled(flag);
            this.txtDescripcion.setEnabled(flag);
            this.txtMensaje.setEnabled(flag);
    }
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = this.tblCanditados1.getSelectedRow();
        String id = this.tblCanditados1.getValueAt(fila, 0).toString();
        ClsMensaje respuesta = this.controladorCandidato.eliminarCandidato(id);

        if(respuesta.getTipo().equals(ClsMensaje.OK)){
            JOptionPane.showMessageDialog(rootPane, respuesta.getTexto());
        }
        ObtenerCandidatos();

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        this.ClearControls();
        this.EnabledControls(true);
        this.btnAdicionar.setEnabled(false);
        this.btnGuardar.setEnabled(true);
        this.btnEditar.setEnabled(false);
        this.btnEliminar.setEnabled(false);
        this.btnCancelar.setEnabled(true); 
        
        this.txtIdentificacion.setEnabled(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        ClsMensaje respuesta;
        
        String tipoDocumento = this.cboxTipoDoc.getSelectedItem().toString();
        String numeroDocumento = this.txtIdentificacion.getText();
        String nombre = this.txtNombre.getText();
        String telefono = this.txtTelefono.getText();
        String eMail = this.txtEmail.getText();
        String partido = this.cboxPartidoPolitico.getSelectedItem().toString();
        String ciudad = this.cboxCiudad.getSelectedItem().toString();
        String descripcion = this.txtDescripcion.getText();
        String mensaje = this.txtMensaje.getText();
        String cargo = this.cboxCargos.getSelectedItem().toString();

        ClsCandidato candidato = new ClsCandidato(partido,ciudad,descripcion,mensaje,cargo,tipoDocumento,numeroDocumento, nombre,telefono,eMail);
        respuesta = this.controladorCandidato.agregarCandidato(candidato);

        if(respuesta.getTipo().equals(ClsMensaje.OK)){
            JOptionPane.showMessageDialog(rootPane, respuesta.getTexto());
        }
        ObtenerCandidatos();
        //llenarCampos();  
        this.EnabledControls(false);
        
        this.btnAdicionar.setEnabled(true);
        this.btnEliminar.setEnabled(true);
        this.btnEditar.setEnabled(true);
        this.btnGuardar.setEnabled(false);
        this.btnActualizar.setEnabled(false); 
        this.btnCancelar.setEnabled(false);
        
              
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.EnabledControls(false); 
        this.btnAdicionar.setEnabled(true);
        this.btnEliminar.setEnabled(true);
        this.btnEditar.setEnabled(true);
        this.btnGuardar.setEnabled(false);
        this.btnActualizar.setEnabled(false); 
        this.btnCancelar.setEnabled(false);
        
        llenarCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.EnabledControls(true);        
        this.btnEditar.setEnabled(false);
        this.btnActualizar.setEnabled(true); 
        this.btnAdicionar.setEnabled(false);
        this.btnEliminar.setEnabled(false);
        this.btnCancelar.setEnabled(true); 
        
        this.txtIdentificacion.setEnabled(false);
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
             
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
  
    }//GEN-LAST:event_formWindowOpened

    private void tblCanditados1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCanditados1KeyPressed
 
    }//GEN-LAST:event_tblCanditados1KeyPressed

    private void tblCanditados1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCanditados1KeyTyped

    }//GEN-LAST:event_tblCanditados1KeyTyped

    private void tblCanditados1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCanditados1KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP)  {
            //this.txtNombre.setText("Down");
            llenarCampos();
        }
    }//GEN-LAST:event_tblCanditados1KeyReleased

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        ClsMensaje respuesta;
        
        String tipoDocumento = this.cboxTipoDoc.getSelectedItem().toString();
        String numeroDocumento = this.txtIdentificacion.getText();
        String nombre = this.txtNombre.getText();
        String telefono = this.txtTelefono.getText();
        String eMail = this.txtEmail.getText();
        String partido = this.cboxPartidoPolitico.getSelectedItem().toString();
        String ciudad = this.cboxCiudad.getSelectedItem().toString();
        String descripcion = this.txtDescripcion.getText();
        String mensaje = this.txtMensaje.getText();
        String cargo = this.cboxCargos.getSelectedItem().toString();

        ClsCandidato candidato = new ClsCandidato(partido,ciudad,descripcion,mensaje,cargo,tipoDocumento,numeroDocumento, nombre,telefono,eMail);
        respuesta = this.controladorCandidato.actualizarCandidato(candidato);

        if(respuesta.getTipo().equals(ClsMensaje.OK)){
            JOptionPane.showMessageDialog(rootPane, respuesta.getTexto());
        }
        ObtenerCandidatos();
        //llenarCampos(); 
        this.EnabledControls(false);
        this.btnAdicionar.setEnabled(true);
        this.btnEliminar.setEnabled(true);
        this.btnEditar.setEnabled(true);
        this.btnGuardar.setEnabled(false);
        this.btnActualizar.setEnabled(false); 
        this.btnCancelar.setEnabled(false);
        
               
        
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnPropuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropuestasActionPerformed
        //this.tblCanditados1.setRowSelectionInterval(0, 0);
        int fila = this.tblCanditados1.getSelectedRow();
        if (fila == -1){
            fila=0;
        }
        parametro = this.tblCanditados1.getValueAt(fila, 0).toString();
        
        this.vistaPropuesta = new VistaPropuesta(this);
        this.vistaPropuesta.setLocationRelativeTo(null);
        this.vistaPropuesta.setVisible(true);
    }//GEN-LAST:event_btnPropuestasActionPerformed
    
   public void ObtenerCandidatos(){
        LinkedList<ClsCandidato> listaCandidatos = this.controladorCandidato.ObtenerCandidatos();
        this.actualizarTabla(listaCandidatos);
    } 

    private void actualizarTabla(LinkedList<ClsCandidato> candidatos){
        DefaultTableModel modelo1 = (DefaultTableModel) this.tblCanditados1.getModel();
        modelo1.setRowCount(0);
        for (ClsCandidato c : candidatos){
            Object[] fila ={c.getNumeroDocumento(),  c.getNombre(),c.getPartidopolitico()};
            modelo1.addRow(fila);
        }
        this.tblCanditados1.getColumnModel().getColumn(0).setMinWidth(0);
        this.tblCanditados1.getColumnModel().getColumn(0).setMaxWidth(0);
        this.tblCanditados1.getColumnModel().getColumn(0).setWidth(0);
    }
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCandidato(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnPropuestas;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cboxCargos;
    private javax.swing.JComboBox<String> cboxCiudad;
    public static javax.swing.JComboBox<String> cboxPartidoPolitico;
    private javax.swing.JComboBox<String> cboxTipoDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblCanditados1;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextArea txtMensaje;
    public static javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
